import { Link } from "@tanstack/react-router";
import { Brain,Shield,Cpu,Sparkles,ArrowRight,Activity } from "lucide-react";
import { useBot4xStore } from "@/lib/bot4x-store";
function Card(p:{title:string;icon:typeof Brain;accent:string;to:string;children:React.ReactNode}){return <div className="rounded-xl border border-border bg-card/60 p-4 flex flex-col gap-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><div className="size-7 rounded-md flex items-center justify-center" style={{color:p.accent}}><p.icon className="size-4"/></div><h3 className="text-[13px] font-medium">{p.title}</h3></div><Link to={p.to} className="text-[11px] text-[var(--brand-cyan)]">Ver mais <ArrowRight className="size-3 inline"/></Link></div><div className="min-h-[68px]">{p.children}</div></div>}
const unavailable=(text:string)=><div className="rounded-lg border border-border bg-secondary/30 p-3 text-[11px] text-muted-foreground">Indisponível nesta fase · {text}</div>;
export function DnaTraderWidget(){return <Card title="DNA Trader" icon={Brain} accent="#378ADD" to="/dna-trader">{unavailable("fonte DNA ainda não conectada")}</Card>}
export function ManipulationWidget(){return <Card title="Manipulation" icon={Shield} accent="#E24B4A" to="/manipulation">{unavailable("fonte real será conectada na Fase 1")}</Card>}
export function SentimentWidget(){return <Card title="Sentiment" icon={Sparkles} accent="#7F77DD" to="/sentiment">{unavailable("endpoint real será conectado na Fase 1")}</Card>}
export function Bot4xSummaryWidget(){const mode=useBot4xStore(s=>s.mode),profile=useBot4xStore(s=>s.profile),leverage=useBot4xStore(s=>s.leverage),pnl=useBot4xStore(s=>s.dailyPnlPct);return <Card title="Bot4x" icon={Cpu} accent="#1D9E75" to="/bot4x"><div className="flex items-center gap-3"><div><div className="text-[10px] uppercase text-muted-foreground">{profile}</div><div className="font-semibold">{mode}</div><div className="text-[11px] text-muted-foreground">{leverage}×</div></div><div><div className="text-[18px] font-semibold">{pnl>=0?"+":""}{pnl.toFixed(2)}%</div><div className="text-[10px] text-muted-foreground"><Activity className="size-3 inline"/> Status real do Bot4x</div></div></div></Card>}
export function IntegrationWidgets(){return <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3"><DnaTraderWidget/><ManipulationWidget/><SentimentWidget/><Bot4xSummaryWidget/></div>}
