/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSentimentRouteImport } from './routes/_authenticated/sentiment'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedManipulationRouteImport } from './routes/_authenticated/manipulation'
import { Route as AuthenticatedDnaTraderRouteImport } from './routes/_authenticated/dna-trader'
import { Route as AuthenticatedDnaPairsRouteImport } from './routes/_authenticated/dna-pairs'
import { Route as AuthenticatedDnaCorrectionsRouteImport } from './routes/_authenticated/dna-corrections'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopyTradingRouteImport } from './routes/_authenticated/copy-trading'
import { Route as AuthenticatedCalibratorRouteImport } from './routes/_authenticated/calibrator'
import { Route as AuthenticatedBot4xRouteImport } from './routes/_authenticated/bot4x'
import { Route as AuthenticatedApiRouteImport } from './routes/_authenticated/api'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiSignalsIndexRouteImport } from './routes/api/signals/index'
import { Route as ApiPricesIndexRouteImport } from './routes/api/prices/index'
import { Route as ApiSignalsIdRouteImport } from './routes/api/signals/$id'
import { Route as ApiSentimentOverviewRouteImport } from './routes/api/sentiment/overview'
import { Route as ApiRiskStatusRouteImport } from './routes/api/risk/status'
import { Route as ApiRiskEvaluateRouteImport } from './routes/api/risk/evaluate'
import { Route as ApiPricesSymbolRouteImport } from './routes/api/prices/$symbol'
import { Route as ApiMarketplaceProductsRouteImport } from './routes/api/marketplace/products'
import { Route as ApiMarketplaceHistoryRouteImport } from './routes/api/marketplace/history'
import { Route as ApiMarketScoreDistributionRouteImport } from './routes/api/market/score-distribution'
import { Route as ApiMarketHistoryRouteImport } from './routes/api/market/history'
import { Route as ApiMarketCalendarRouteImport } from './routes/api/market/calendar'
import { Route as ApiMarketRegimeCurrentRouteImport } from './routes/api/market-regime/current'
import { Route as ApiManipulationAlertsRouteImport } from './routes/api/manipulation/alerts'
import { Route as ApiExchangeTestRouteImport } from './routes/api/exchange/test'
import { Route as ApiExchangeCredentialsRouteImport } from './routes/api/exchange/credentials'
import { Route as ApiDnaStatsRouteImport } from './routes/api/dna/stats'
import { Route as ApiCopyFollowsRouteImport } from './routes/api/copy/follows'
import { Route as ApiCopilotHistoryRouteImport } from './routes/api/copilot/history'
import { Route as ApiCopilotChatRouteImport } from './routes/api/copilot/chat'
import { Route as ApiBot4xTelemetryRouteImport } from './routes/api/bot4x/telemetry'
import { Route as ApiBot4xStopRouteImport } from './routes/api/bot4x/stop'
import { Route as ApiBot4xStartRouteImport } from './routes/api/bot4x/start'
import { Route as ApiBot4xExecutionsRouteImport } from './routes/api/bot4x/executions'
import { Route as ApiBot4xConfigRouteImport } from './routes/api/bot4x/config'
import { Route as ApiBot4xBalanceRouteImport } from './routes/api/bot4x/balance'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAlertsSettingsRouteImport } from './routes/api/alerts/settings'
import { Route as ApiAlertsFeedRouteImport } from './routes/api/alerts/feed'
import { Route as AuthenticatedCalibratorHistoryRouteImport } from './routes/_authenticated/calibrator.history'
import { Route as AuthenticatedBot4xOnboardingRouteImport } from './routes/_authenticated/bot4x.onboarding'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiSentimentAssetSymbolRouteImport } from './routes/api/sentiment/asset.$symbol'
import { Route as ApiManipulationSnapshotPairRouteImport } from './routes/api/manipulation/snapshot.$pair'
import { Route as ApiDnaProfileUserIdRouteImport } from './routes/api/dna/profile/$userId'
import { Route as ApiCalibratorStateUserIdRouteImport } from './routes/api/calibrator/state.$userId'
import { Route as ApiCalibratorRunUserIdRouteImport } from './routes/api/calibrator/run.$userId'
import { Route as ApiCalibratorIntentUserIdRouteImport } from './routes/api/calibrator/intent.$userId'
import { Route as ApiCalibratorFeedbackUserIdRouteImport } from './routes/api/calibrator/feedback.$userId'
import { Route as ApiBot4xExecutionsExportRouteImport } from './routes/api/bot4x/executions.export'
import { Route as AuthenticatedCalibratorHistoryIdRouteImport } from './routes/_authenticated/calibrator.history.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSentimentRoute = AuthenticatedSentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManipulationRoute =
  AuthenticatedManipulationRouteImport.update({
    id: '/manipulation',
    path: '/manipulation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDnaTraderRoute = AuthenticatedDnaTraderRouteImport.update({
  id: '/dna-trader',
  path: '/dna-trader',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDnaPairsRoute = AuthenticatedDnaPairsRouteImport.update({
  id: '/dna-pairs',
  path: '/dna-pairs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDnaCorrectionsRoute =
  AuthenticatedDnaCorrectionsRouteImport.update({
    id: '/dna-corrections',
    path: '/dna-corrections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCopyTradingRoute =
  AuthenticatedCopyTradingRouteImport.update({
    id: '/copy-trading',
    path: '/copy-trading',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalibratorRoute = AuthenticatedCalibratorRouteImport.update({
  id: '/calibrator',
  path: '/calibrator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBot4xRoute = AuthenticatedBot4xRouteImport.update({
  id: '/bot4x',
  path: '/bot4x',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiRoute = AuthenticatedApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSignalsIndexRoute = ApiSignalsIndexRouteImport.update({
  id: '/api/signals/',
  path: '/api/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesIndexRoute = ApiPricesIndexRouteImport.update({
  id: '/api/prices/',
  path: '/api/prices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsIdRoute = ApiSignalsIdRouteImport.update({
  id: '/api/signals/$id',
  path: '/api/signals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentimentOverviewRoute = ApiSentimentOverviewRouteImport.update({
  id: '/api/sentiment/overview',
  path: '/api/sentiment/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRiskStatusRoute = ApiRiskStatusRouteImport.update({
  id: '/api/risk/status',
  path: '/api/risk/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRiskEvaluateRoute = ApiRiskEvaluateRouteImport.update({
  id: '/api/risk/evaluate',
  path: '/api/risk/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesSymbolRoute = ApiPricesSymbolRouteImport.update({
  id: '/api/prices/$symbol',
  path: '/api/prices/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceProductsRoute = ApiMarketplaceProductsRouteImport.update({
  id: '/api/marketplace/products',
  path: '/api/marketplace/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceHistoryRoute = ApiMarketplaceHistoryRouteImport.update({
  id: '/api/marketplace/history',
  path: '/api/marketplace/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketScoreDistributionRoute =
  ApiMarketScoreDistributionRouteImport.update({
    id: '/api/market/score-distribution',
    path: '/api/market/score-distribution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketHistoryRoute = ApiMarketHistoryRouteImport.update({
  id: '/api/market/history',
  path: '/api/market/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCalendarRoute = ApiMarketCalendarRouteImport.update({
  id: '/api/market/calendar',
  path: '/api/market/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketRegimeCurrentRoute = ApiMarketRegimeCurrentRouteImport.update({
  id: '/api/market-regime/current',
  path: '/api/market-regime/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManipulationAlertsRoute = ApiManipulationAlertsRouteImport.update({
  id: '/api/manipulation/alerts',
  path: '/api/manipulation/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeTestRoute = ApiExchangeTestRouteImport.update({
  id: '/api/exchange/test',
  path: '/api/exchange/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeCredentialsRoute = ApiExchangeCredentialsRouteImport.update({
  id: '/api/exchange/credentials',
  path: '/api/exchange/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDnaStatsRoute = ApiDnaStatsRouteImport.update({
  id: '/api/dna/stats',
  path: '/api/dna/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopyFollowsRoute = ApiCopyFollowsRouteImport.update({
  id: '/api/copy/follows',
  path: '/api/copy/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotHistoryRoute = ApiCopilotHistoryRouteImport.update({
  id: '/api/copilot/history',
  path: '/api/copilot/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotChatRoute = ApiCopilotChatRouteImport.update({
  id: '/api/copilot/chat',
  path: '/api/copilot/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xTelemetryRoute = ApiBot4xTelemetryRouteImport.update({
  id: '/api/bot4x/telemetry',
  path: '/api/bot4x/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xStopRoute = ApiBot4xStopRouteImport.update({
  id: '/api/bot4x/stop',
  path: '/api/bot4x/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xStartRoute = ApiBot4xStartRouteImport.update({
  id: '/api/bot4x/start',
  path: '/api/bot4x/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xExecutionsRoute = ApiBot4xExecutionsRouteImport.update({
  id: '/api/bot4x/executions',
  path: '/api/bot4x/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xConfigRoute = ApiBot4xConfigRouteImport.update({
  id: '/api/bot4x/config',
  path: '/api/bot4x/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xBalanceRoute = ApiBot4xBalanceRouteImport.update({
  id: '/api/bot4x/balance',
  path: '/api/bot4x/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsSettingsRoute = ApiAlertsSettingsRouteImport.update({
  id: '/api/alerts/settings',
  path: '/api/alerts/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsFeedRoute = ApiAlertsFeedRouteImport.update({
  id: '/api/alerts/feed',
  path: '/api/alerts/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalibratorHistoryRoute =
  AuthenticatedCalibratorHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedCalibratorRoute,
  } as any)
const AuthenticatedBot4xOnboardingRoute =
  AuthenticatedBot4xOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedBot4xRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSentimentAssetSymbolRoute = ApiSentimentAssetSymbolRouteImport.update({
  id: '/api/sentiment/asset/$symbol',
  path: '/api/sentiment/asset/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManipulationSnapshotPairRoute =
  ApiManipulationSnapshotPairRouteImport.update({
    id: '/api/manipulation/snapshot/$pair',
    path: '/api/manipulation/snapshot/$pair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDnaProfileUserIdRoute = ApiDnaProfileUserIdRouteImport.update({
  id: '/api/dna/profile/$userId',
  path: '/api/dna/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalibratorStateUserIdRoute =
  ApiCalibratorStateUserIdRouteImport.update({
    id: '/api/calibrator/state/$userId',
    path: '/api/calibrator/state/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalibratorRunUserIdRoute = ApiCalibratorRunUserIdRouteImport.update({
  id: '/api/calibrator/run/$userId',
  path: '/api/calibrator/run/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalibratorIntentUserIdRoute =
  ApiCalibratorIntentUserIdRouteImport.update({
    id: '/api/calibrator/intent/$userId',
    path: '/api/calibrator/intent/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalibratorFeedbackUserIdRoute =
  ApiCalibratorFeedbackUserIdRouteImport.update({
    id: '/api/calibrator/feedback/$userId',
    path: '/api/calibrator/feedback/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBot4xExecutionsExportRoute =
  ApiBot4xExecutionsExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => ApiBot4xExecutionsRoute,
  } as any)
const AuthenticatedCalibratorHistoryIdRoute =
  AuthenticatedCalibratorHistoryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCalibratorHistoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/api': typeof AuthenticatedApiRoute
  '/bot4x': typeof AuthenticatedBot4xRouteWithChildren
  '/calibrator': typeof AuthenticatedCalibratorRouteWithChildren
  '/copy-trading': typeof AuthenticatedCopyTradingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/dna-corrections': typeof AuthenticatedDnaCorrectionsRoute
  '/dna-pairs': typeof AuthenticatedDnaPairsRoute
  '/dna-trader': typeof AuthenticatedDnaTraderRoute
  '/manipulation': typeof AuthenticatedManipulationRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sentiment': typeof AuthenticatedSentimentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/bot4x/onboarding': typeof AuthenticatedBot4xOnboardingRoute
  '/calibrator/history': typeof AuthenticatedCalibratorHistoryRouteWithChildren
  '/api/alerts/feed': typeof ApiAlertsFeedRoute
  '/api/alerts/settings': typeof ApiAlertsSettingsRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bot4x/balance': typeof ApiBot4xBalanceRoute
  '/api/bot4x/config': typeof ApiBot4xConfigRoute
  '/api/bot4x/executions': typeof ApiBot4xExecutionsRouteWithChildren
  '/api/bot4x/start': typeof ApiBot4xStartRoute
  '/api/bot4x/stop': typeof ApiBot4xStopRoute
  '/api/bot4x/telemetry': typeof ApiBot4xTelemetryRoute
  '/api/copilot/chat': typeof ApiCopilotChatRoute
  '/api/copilot/history': typeof ApiCopilotHistoryRoute
  '/api/copy/follows': typeof ApiCopyFollowsRoute
  '/api/dna/stats': typeof ApiDnaStatsRoute
  '/api/exchange/credentials': typeof ApiExchangeCredentialsRoute
  '/api/exchange/test': typeof ApiExchangeTestRoute
  '/api/manipulation/alerts': typeof ApiManipulationAlertsRoute
  '/api/market-regime/current': typeof ApiMarketRegimeCurrentRoute
  '/api/market/history': typeof ApiMarketHistoryRoute
  '/api/market/calendar': typeof ApiMarketCalendarRoute
  '/api/market/score-distribution': typeof ApiMarketScoreDistributionRoute
  '/api/marketplace/history': typeof ApiMarketplaceHistoryRoute
  '/api/marketplace/products': typeof ApiMarketplaceProductsRoute
  '/api/prices/$symbol': typeof ApiPricesSymbolRoute
  '/api/risk/evaluate': typeof ApiRiskEvaluateRoute
  '/api/risk/status': typeof ApiRiskStatusRoute
  '/api/sentiment/overview': typeof ApiSentimentOverviewRoute
  '/api/signals/$id': typeof ApiSignalsIdRoute
  '/api/prices/': typeof ApiPricesIndexRoute
  '/api/signals/': typeof ApiSignalsIndexRoute
  '/calibrator/history/$id': typeof AuthenticatedCalibratorHistoryIdRoute
  '/api/bot4x/executions/export': typeof ApiBot4xExecutionsExportRoute
  '/api/calibrator/feedback/$userId': typeof ApiCalibratorFeedbackUserIdRoute
  '/api/calibrator/intent/$userId': typeof ApiCalibratorIntentUserIdRoute
  '/api/calibrator/run/$userId': typeof ApiCalibratorRunUserIdRoute
  '/api/calibrator/state/$userId': typeof ApiCalibratorStateUserIdRoute
  '/api/dna/profile/$userId': typeof ApiDnaProfileUserIdRoute
  '/api/manipulation/snapshot/$pair': typeof ApiManipulationSnapshotPairRoute
  '/api/sentiment/asset/$symbol': typeof ApiSentimentAssetSymbolRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/api': typeof AuthenticatedApiRoute
  '/bot4x': typeof AuthenticatedBot4xRouteWithChildren
  '/calibrator': typeof AuthenticatedCalibratorRouteWithChildren
  '/copy-trading': typeof AuthenticatedCopyTradingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/dna-corrections': typeof AuthenticatedDnaCorrectionsRoute
  '/dna-pairs': typeof AuthenticatedDnaPairsRoute
  '/dna-trader': typeof AuthenticatedDnaTraderRoute
  '/manipulation': typeof AuthenticatedManipulationRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sentiment': typeof AuthenticatedSentimentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/bot4x/onboarding': typeof AuthenticatedBot4xOnboardingRoute
  '/calibrator/history': typeof AuthenticatedCalibratorHistoryRouteWithChildren
  '/api/alerts/feed': typeof ApiAlertsFeedRoute
  '/api/alerts/settings': typeof ApiAlertsSettingsRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bot4x/balance': typeof ApiBot4xBalanceRoute
  '/api/bot4x/config': typeof ApiBot4xConfigRoute
  '/api/bot4x/executions': typeof ApiBot4xExecutionsRouteWithChildren
  '/api/bot4x/start': typeof ApiBot4xStartRoute
  '/api/bot4x/stop': typeof ApiBot4xStopRoute
  '/api/bot4x/telemetry': typeof ApiBot4xTelemetryRoute
  '/api/copilot/chat': typeof ApiCopilotChatRoute
  '/api/copilot/history': typeof ApiCopilotHistoryRoute
  '/api/copy/follows': typeof ApiCopyFollowsRoute
  '/api/dna/stats': typeof ApiDnaStatsRoute
  '/api/exchange/credentials': typeof ApiExchangeCredentialsRoute
  '/api/exchange/test': typeof ApiExchangeTestRoute
  '/api/manipulation/alerts': typeof ApiManipulationAlertsRoute
  '/api/market-regime/current': typeof ApiMarketRegimeCurrentRoute
  '/api/market/history': typeof ApiMarketHistoryRoute
  '/api/market/calendar': typeof ApiMarketCalendarRoute
  '/api/market/score-distribution': typeof ApiMarketScoreDistributionRoute
  '/api/marketplace/history': typeof ApiMarketplaceHistoryRoute
  '/api/marketplace/products': typeof ApiMarketplaceProductsRoute
  '/api/prices/$symbol': typeof ApiPricesSymbolRoute
  '/api/risk/evaluate': typeof ApiRiskEvaluateRoute
  '/api/risk/status': typeof ApiRiskStatusRoute
  '/api/sentiment/overview': typeof ApiSentimentOverviewRoute
  '/api/signals/$id': typeof ApiSignalsIdRoute
  '/api/prices': typeof ApiPricesIndexRoute
  '/api/signals': typeof ApiSignalsIndexRoute
  '/calibrator/history/$id': typeof AuthenticatedCalibratorHistoryIdRoute
  '/api/bot4x/executions/export': typeof ApiBot4xExecutionsExportRoute
  '/api/calibrator/feedback/$userId': typeof ApiCalibratorFeedbackUserIdRoute
  '/api/calibrator/intent/$userId': typeof ApiCalibratorIntentUserIdRoute
  '/api/calibrator/run/$userId': typeof ApiCalibratorRunUserIdRoute
  '/api/calibrator/state/$userId': typeof ApiCalibratorStateUserIdRoute
  '/api/dna/profile/$userId': typeof ApiDnaProfileUserIdRoute
  '/api/manipulation/snapshot/$pair': typeof ApiManipulationSnapshotPairRoute
  '/api/sentiment/asset/$symbol': typeof ApiSentimentAssetSymbolRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/api': typeof AuthenticatedApiRoute
  '/_authenticated/bot4x': typeof AuthenticatedBot4xRouteWithChildren
  '/_authenticated/calibrator': typeof AuthenticatedCalibratorRouteWithChildren
  '/_authenticated/copy-trading': typeof AuthenticatedCopyTradingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/dna-corrections': typeof AuthenticatedDnaCorrectionsRoute
  '/_authenticated/dna-pairs': typeof AuthenticatedDnaPairsRoute
  '/_authenticated/dna-trader': typeof AuthenticatedDnaTraderRoute
  '/_authenticated/manipulation': typeof AuthenticatedManipulationRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sentiment': typeof AuthenticatedSentimentRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRoute
  '/_authenticated/bot4x/onboarding': typeof AuthenticatedBot4xOnboardingRoute
  '/_authenticated/calibrator/history': typeof AuthenticatedCalibratorHistoryRouteWithChildren
  '/api/alerts/feed': typeof ApiAlertsFeedRoute
  '/api/alerts/settings': typeof ApiAlertsSettingsRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bot4x/balance': typeof ApiBot4xBalanceRoute
  '/api/bot4x/config': typeof ApiBot4xConfigRoute
  '/api/bot4x/executions': typeof ApiBot4xExecutionsRouteWithChildren
  '/api/bot4x/start': typeof ApiBot4xStartRoute
  '/api/bot4x/stop': typeof ApiBot4xStopRoute
  '/api/bot4x/telemetry': typeof ApiBot4xTelemetryRoute
  '/api/copilot/chat': typeof ApiCopilotChatRoute
  '/api/copilot/history': typeof ApiCopilotHistoryRoute
  '/api/copy/follows': typeof ApiCopyFollowsRoute
  '/api/dna/stats': typeof ApiDnaStatsRoute
  '/api/exchange/credentials': typeof ApiExchangeCredentialsRoute
  '/api/exchange/test': typeof ApiExchangeTestRoute
  '/api/manipulation/alerts': typeof ApiManipulationAlertsRoute
  '/api/market-regime/current': typeof ApiMarketRegimeCurrentRoute
  '/api/market/history': typeof ApiMarketHistoryRoute
  '/api/market/score-distribution': typeof ApiMarketScoreDistributionRoute
  '/api/marketplace/history': typeof ApiMarketplaceHistoryRoute
  '/api/marketplace/products': typeof ApiMarketplaceProductsRoute
  '/api/prices/$symbol': typeof ApiPricesSymbolRoute
  '/api/risk/evaluate': typeof ApiRiskEvaluateRoute
  '/api/risk/status': typeof ApiRiskStatusRoute
  '/api/sentiment/overview': typeof ApiSentimentOverviewRoute
  '/api/signals/$id': typeof ApiSignalsIdRoute
  '/api/prices/': typeof ApiPricesIndexRoute
  '/api/signals/': typeof ApiSignalsIndexRoute
  '/_authenticated/calibrator/history/$id': typeof AuthenticatedCalibratorHistoryIdRoute
  '/api/bot4x/executions/export': typeof ApiBot4xExecutionsExportRoute
  '/api/calibrator/feedback/$userId': typeof ApiCalibratorFeedbackUserIdRoute
  '/api/calibrator/intent/$userId': typeof ApiCalibratorIntentUserIdRoute
  '/api/calibrator/run/$userId': typeof ApiCalibratorRunUserIdRoute
  '/api/calibrator/state/$userId': typeof ApiCalibratorStateUserIdRoute
  '/api/dna/profile/$userId': typeof ApiDnaProfileUserIdRoute
  '/api/manipulation/snapshot/$pair': typeof ApiManipulationSnapshotPairRoute
  '/api/sentiment/asset/$symbol': typeof ApiSentimentAssetSymbolRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/alerts'
    | '/api'
    | '/bot4x'
    | '/calibrator'
    | '/copy-trading'
    | '/dashboard'
    | '/diagnostics'
    | '/dna-corrections'
    | '/dna-pairs'
    | '/dna-trader'
    | '/manipulation'
    | '/marketplace'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/sentiment'
    | '/settings'
    | '/signals'
    | '/bot4x/onboarding'
    | '/calibrator/history'
    | '/api/alerts/feed'
    | '/api/alerts/settings'
    | '/api/auth/me'
    | '/api/bot4x/balance'
    | '/api/bot4x/config'
    | '/api/bot4x/executions'
    | '/api/bot4x/start'
    | '/api/bot4x/stop'
    | '/api/bot4x/telemetry'
    | '/api/copilot/chat'
    | '/api/copilot/history'
    | '/api/copy/follows'
    | '/api/dna/stats'
    | '/api/exchange/credentials'
    | '/api/exchange/test'
    | '/api/manipulation/alerts'
    | '/api/market-regime/current'
    | '/api/market/history'
    | '/api/market/calendar'
    | '/api/market/score-distribution'
    | '/api/marketplace/history'
    | '/api/marketplace/products'
    | '/api/prices/$symbol'
    | '/api/risk/evaluate'
    | '/api/risk/status'
    | '/api/sentiment/overview'
    | '/api/signals/$id'
    | '/api/prices/'
    | '/api/signals/'
    | '/calibrator/history/$id'
    | '/api/bot4x/executions/export'
    | '/api/calibrator/feedback/$userId'
    | '/api/calibrator/intent/$userId'
    | '/api/calibrator/run/$userId'
    | '/api/calibrator/state/$userId'
    | '/api/dna/profile/$userId'
    | '/api/manipulation/snapshot/$pair'
    | '/api/sentiment/asset/$symbol'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/alerts'
    | '/api'
    | '/bot4x'
    | '/calibrator'
    | '/copy-trading'
    | '/dashboard'
    | '/diagnostics'
    | '/dna-corrections'
    | '/dna-pairs'
    | '/dna-trader'
    | '/manipulation'
    | '/marketplace'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/sentiment'
    | '/settings'
    | '/signals'
    | '/bot4x/onboarding'
    | '/calibrator/history'
    | '/api/alerts/feed'
    | '/api/alerts/settings'
    | '/api/auth/me'
    | '/api/bot4x/balance'
    | '/api/bot4x/config'
    | '/api/bot4x/executions'
    | '/api/bot4x/start'
    | '/api/bot4x/stop'
    | '/api/bot4x/telemetry'
    | '/api/copilot/chat'
    | '/api/copilot/history'
    | '/api/copy/follows'
    | '/api/dna/stats'
    | '/api/exchange/credentials'
    | '/api/exchange/test'
    | '/api/manipulation/alerts'
    | '/api/market-regime/current'
    | '/api/market/history'
    | '/api/market/calendar'
    | '/api/market/score-distribution'
    | '/api/marketplace/history'
    | '/api/marketplace/products'
    | '/api/prices/$symbol'
    | '/api/risk/evaluate'
    | '/api/risk/status'
    | '/api/sentiment/overview'
    | '/api/signals/$id'
    | '/api/prices'
    | '/api/signals'
    | '/calibrator/history/$id'
    | '/api/bot4x/executions/export'
    | '/api/calibrator/feedback/$userId'
    | '/api/calibrator/intent/$userId'
    | '/api/calibrator/run/$userId'
    | '/api/calibrator/state/$userId'
    | '/api/dna/profile/$userId'
    | '/api/manipulation/snapshot/$pair'
    | '/api/sentiment/asset/$symbol'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/alerts'
    | '/_authenticated/api'
    | '/_authenticated/bot4x'
    | '/_authenticated/calibrator'
    | '/_authenticated/copy-trading'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostics'
    | '/_authenticated/dna-corrections'
    | '/_authenticated/dna-pairs'
    | '/_authenticated/dna-trader'
    | '/_authenticated/manipulation'
    | '/_authenticated/marketplace'
    | '/_authenticated/onboarding'
    | '/_authenticated/pricing'
    | '/_authenticated/profile'
    | '/_authenticated/sentiment'
    | '/_authenticated/settings'
    | '/_authenticated/signals'
    | '/_authenticated/bot4x/onboarding'
    | '/_authenticated/calibrator/history'
    | '/api/alerts/feed'
    | '/api/alerts/settings'
    | '/api/auth/me'
    | '/api/bot4x/balance'
    | '/api/bot4x/config'
    | '/api/bot4x/executions'
    | '/api/bot4x/start'
    | '/api/bot4x/stop'
    | '/api/bot4x/telemetry'
    | '/api/copilot/chat'
    | '/api/copilot/history'
    | '/api/copy/follows'
    | '/api/dna/stats'
    | '/api/exchange/credentials'
    | '/api/exchange/test'
    | '/api/manipulation/alerts'
    | '/api/market-regime/current'
    | '/api/market/history'
    | '/api/market/calendar'
    | '/api/market/score-distribution'
    | '/api/marketplace/history'
    | '/api/marketplace/products'