/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSentimentRouteImport } from './routes/_authenticated/sentiment'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedManipulationRouteImport } from './routes/_authenticated/manipulation'
import { Route as AuthenticatedDnaTraderRouteImport } from './routes/_authenticated/dna-trader'
import { Route as AuthenticatedDnaPairsRouteImport } from './routes/_authenticated/dna-pairs'
import { Route as AuthenticatedDnaCorrectionsRouteImport } from './routes/_authenticated/dna-corrections'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopyTradingRouteImport } from './routes/_authenticated/copy-trading'
import { Route as AuthenticatedCalibratorRouteImport } from './routes/_authenticated/calibrator'
import { Route as AuthenticatedBot4xRouteImport } from './routes/_authenticated/bot4x'
import { Route as AuthenticatedApiRouteImport } from './routes/_authenticated/api'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiSignalsIndexRouteImport } from './routes/api/signals/index'
import { Route as ApiPricesIndexRouteImport } from './routes/api/prices/index'
import { Route as ApiSignalsIdRouteImport } from './routes/api/signals/$id'
import { Route as ApiSentimentOverviewRouteImport } from './routes/api/sentiment/overview'
import { Route as ApiRiskStatusRouteImport } from './routes/api/risk/status'
import { Route as ApiRiskEvaluateRouteImport } from './routes/api/risk/evaluate'
import { Route as ApiPricesSymbolRouteImport } from './routes/api/prices/$symbol'
import { Route as ApiMarketplaceProductsRouteImport } from './routes/api/marketplace/products'
import { Route as ApiMarketplaceHistoryRouteImport } from './routes/api/marketplace/history'
import { Route as ApiMarketScoreDistributionRouteImport } from './routes/api/market/score-distribution'
import { Route as ApiMarketHistoryRouteImport } from './routes/api/market/history'
import { Route as ApiMarketCalendarRouteImport } from './routes/api/market/calendar'
import { Route as ApiMarketRegimeCurrentRouteImport } from './routes/api/market-regime/current'
import { Route as ApiManipulationAlertsRouteImport } from './routes/api/manipulation/alerts'
import { Route as ApiExchangeTestRouteImport } from './routes/api/exchange/test'
import { Route as ApiExchangeCredentialsRouteImport } from './routes/api/exchange/credentials'
import { Route as ApiDnaStatsRouteImport } from './routes/api/dna/stats'
import { Route as ApiCopyFollowsRouteImport } from './routes/api/copy/follows'
import { Route as ApiCopilotHistoryRouteImport } from './routes/api/copilot/history'
import { Route as ApiCopilotChatRouteImport } from './routes/api/copilot/chat'
import { Route as ApiBot4xTelemetryRouteImport } from './routes/api/bot4x/telemetry'
import { Route as ApiBot4xStopRouteImport } from './routes/api/bot4x/stop'
import { Route as ApiBot4xStartRouteImport } from './routes/api/bot4x/start'
import { Route as ApiBot4xExecutionsRouteImport } from './routes/api/bot4x/executions'
import { Route as ApiBot4xConfigRouteImport } from './routes/api/bot4x/config'
import { Route as ApiBot4xBalanceRouteImport } from './routes/api/bot4x/balance'
import { Route as ApiBot4xDemoOrderRouteImport } from './routes/api/bot4x/demo-order'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAlertsSettingsRouteImport } from './routes/api/alerts/settings'
import { Route as ApiAlertsFeedRouteImport } from './routes/api/alerts/feed'
import { Route as AuthenticatedCalibratorHistoryRouteImport } from './routes/_authenticated/calibrator.history'
import { Route as AuthenticatedBot4xOnboardingRouteImport } from './routes/_authenticated/bot4x.onboarding'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiSentimentAssetSymbolRouteImport } from './routes/api/sentiment/asset.$symbol'
import { Route as ApiManipulationSnapshotPairRouteImport } from './routes/api/manipulation/snapshot.$pair'
import { Route as ApiDnaProfileUserIdRouteImport } from './routes/api/dna/profile/$userId'
import { Route as ApiCalibratorStateUserIdRouteImport } from './routes/api/calibrator/state.$userId'
import { Route as ApiCalibratorRunUserIdRouteImport } from './routes/api/calibrator/run.$userId'
import { Route as ApiCalibratorIntentUserIdRouteImport } from './routes/api/calibrator/intent.$userId'
import { Route as ApiCalibratorFeedbackUserIdRouteImport } from './routes/api/calibrator/feedback.$userId'
import { Route as ApiBot4xExecutionsExportRouteImport } from './routes/api/bot4x/executions.export'
import { Route as AuthenticatedCalibratorHistoryIdRouteImport } from './routes/_authenticated/calibrator.history.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSentimentRoute = AuthenticatedSentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManipulationRoute =
  AuthenticatedManipulationRouteImport.update({
    id: '/manipulation',
    path: '/manipulation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDnaTraderRoute = AuthenticatedDnaTraderRouteImport.update({
  id: '/dna-trader',
  path: '/dna-trader',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDnaPairsRoute = AuthenticatedDnaPairsRouteImport.update({
  id: '/dna-pairs',
  path: '/dna-pairs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDnaCorrectionsRoute =
  AuthenticatedDnaCorrectionsRouteImport.update({
    id: '/dna-corrections',
    path: '/dna-corrections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCopyTradingRoute =
  AuthenticatedCopyTradingRouteImport.update({
    id: '/copy-trading',
    path: '/copy-trading',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalibratorRoute = AuthenticatedCalibratorRouteImport.update({
  id: '/calibrator',
  path: '/calibrator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBot4xRoute = AuthenticatedBot4xRouteImport.update({
  id: '/bot4x',
  path: '/bot4x',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiRoute = AuthenticatedApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSignalsIndexRoute = ApiSignalsIndexRouteImport.update({
  id: '/api/signals/',
  path: '/api/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesIndexRoute = ApiPricesIndexRouteImport.update({
  id: '/api/prices/',
  path: '/api/prices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsIdRoute = ApiSignalsIdRouteImport.update({
  id: '/api/signals/$id',
  path: '/api/signals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentimentOverviewRoute = ApiSentimentOverviewRouteImport.update({
  id: '/api/sentiment/overview',
  path: '/api/sentiment/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRiskStatusRoute = ApiRiskStatusRouteImport.update({
  id: '/api/risk/status',
  path: '/api/risk/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRiskEvaluateRoute = ApiRiskEvaluateRouteImport.update({
  id: '/api/risk/evaluate',
  path: '/api/risk/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesSymbolRoute = ApiPricesSymbolRouteImport.update({
  id: '/api/prices/$symbol',
  path: '/api/prices/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceProductsRoute = ApiMarketplaceProductsRouteImport.update({
  id: '/api/marketplace/products',
  path: '/api/marketplace/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketplaceHistoryRoute = ApiMarketplaceHistoryRouteImport.update({
  id: '/api/marketplace/history',
  path: '/api/marketplace/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketScoreDistributionRoute =
  ApiMarketScoreDistributionRouteImport.update({
    id: '/api/market/score-distribution',
    path: '/api/market/score-distribution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarketHistoryRoute = ApiMarketHistoryRouteImport.update({
  id: '/api/market/history',
  path: '/api/market/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCalendarRoute = ApiMarketCalendarRouteImport.update({
  id: '/api/market/calendar',
  path: '/api/market/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketRegimeCurrentRoute = ApiMarketRegimeCurrentRouteImport.update({
  id: '/api/market-regime/current',
  path: '/api/market-regime/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManipulationAlertsRoute = ApiManipulationAlertsRouteImport.update({
  id: '/api/manipulation/alerts',
  path: '/api/manipulation/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeTestRoute = ApiExchangeTestRouteImport.update({
  id: '/api/exchange/test',
  path: '/api/exchange/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeCredentialsRoute = ApiExchangeCredentialsRouteImport.update({
  id: '/api/exchange/credentials',
  path: '/api/exchange/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDnaStatsRoute = ApiDnaStatsRouteImport.update({
  id: '/api/dna/stats',
  path: '/api/dna/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopyFollowsRoute = ApiCopyFollowsRouteImport.update({
  id: '/api/copy/follows',
  path: '/api/copy/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotHistoryRoute = ApiCopilotHistoryRouteImport.update({
  id: '/api/copilot/history',
  path: '/api/copilot/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotChatRoute = ApiCopilotChatRouteImport.update({
  id: '/api/copilot/chat',
  path: '/api/copilot/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xTelemetryRoute = ApiBot4xTelemetryRouteImport.update({
  id: '/api/bot4x/telemetry',
  path: '/api/bot4x/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xStopRoute = ApiBot4xStopRouteImport.update({
  id: '/api/bot4x/stop',
  path: '/api/bot4x/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xStartRoute = ApiBot4xStartRouteImport.update({
  id: '/api/bot4x/start',
  path: '/api/bot4x/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xExecutionsRoute = ApiBot4xExecutionsRouteImport.update({
  id: '/api/bot4x/executions',
  path: '/api/bot4x/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xConfigRoute = ApiBot4xConfigRouteImport.update({
  id: '/api/bot4x/config',
  path: '/api/bot4x/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xDemoOrderRoute = ApiBot4xDemoOrderRouteImport.update({
  id: '/api/bot4x/demo-order',
  path: '/api/bot4x/demo-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBot4xBalanceRoute = ApiBot4xBalanceRouteImport.update({
  id: '/api/bot4x/balance',
  path: '/api/bot4x/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsSettingsRoute = ApiAlertsSettingsRouteImport.update({
  id: '/api/alerts/settings',
  path: '/api/alerts/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsFeedRoute = ApiAlertsFeedRouteImport.update({
  id: '/api/alerts/feed',
  path: '/api/alerts/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalibratorHistoryRoute =
  AuthenticatedCalibratorHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedCalibratorRoute,
  } as any)
const AuthenticatedBot4xOnboardingRoute =
  AuthenticatedBot4xOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedBot4xRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSentimentAssetSymbolRoute = ApiSentimentAssetSymbolRouteImport.update({
  id: '/api/sentiment/asset/$symbol',
  path: '/api/sentiment/asset/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManipulationSnapshotPairRoute =
  ApiManipulationSnapshotPairRouteImport.update({
    id: '/api/manipulation/snapshot/$pair',
    path: '/api/manipulation/snapshot/$pair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDnaProfileUserIdRoute = ApiDnaProfileUserIdRouteImport.update({
  id: '/api/dna/profile/$userId',
  path: '/api/dna/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalibratorStateUserIdRoute =
  ApiCalibratorStateUserIdRouteImport.update({
    id: '/api/calibrator/state/$userId',
    path: '/api/calibrator/state/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalibratorRunUserIdRoute = ApiCalibratorRunUserIdRouteImport.update({
  id: '/api/calibrator/run/$userId',
  path: '/api/calibrator/run/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalibratorIntentUserIdRoute =
  ApiCalibratorIntentUserIdRouteImport.update({
    id: '/api/calibrator/intent/$userId',
    path: '/api/calibrator/intent/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalibratorFeedbackUserIdRoute =
  ApiCalibratorFeedbackUserIdRouteImport.update({
    id: '/api/calibrator/feedback/$userId',
    path: '/api/calibrator/feedback/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBot4xExecutionsExportRoute =
  ApiBot4xExecutionsExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => ApiBot4xExecutionsRoute,
  } as any)
const AuthenticatedCalibratorHistoryIdRoute =
  AuthenticatedCalibratorHistoryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCalibratorHistoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/api': typeof AuthenticatedApiRoute
  '/bot4x': typeof AuthenticatedBot4xRouteWithChildren
  '/calibrator': typeof AuthenticatedCalibratorRouteWithChildren
  '/copy-trading': typeof AuthenticatedCopyTradingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/dna-corrections': typeof AuthenticatedDnaCorrectionsRoute
  '/dna-pairs': typeof AuthenticatedDnaPairsRoute
  '/dna-trader': typeof AuthenticatedDnaTraderRoute
  '/manipulation': typeof AuthenticatedManipulationRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sentiment': typeof AuthenticatedSentimentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/bot4x/onboarding': typeof AuthenticatedBot4xOnboardingRoute
  '/calibrator/history': typeof AuthenticatedCalibratorHistoryRouteWithChildren
  '/api/alerts/feed': typeof ApiAlertsFeedRoute
  '/api/alerts/settings': typeof ApiAlertsSettingsRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bot4x/balance': typeof ApiBot4xBalanceRoute
  '/api/bot4x/demo-order': typeof ApiBot4xDemoOrderRoute
  '/api/bot4x/config': typeof ApiBot4xConfigRoute
  '/api/bot4x/executions': typeof ApiBot4xExecutionsRouteWithChildren
  '/api/bot4x/start': typeof ApiBot4xStartRoute
  '/api/bot4x/stop': typeof ApiBot4xStopRoute
  '/api/bot4x/telemetry': typeof ApiBot4xTelemetryRoute
  '/api/copilot/chat': typeof ApiCopilotChatRoute
  '/api/copilot/history': typeof ApiCopilotHistoryRoute
  '/api/copy/follows': typeof ApiCopyFollowsRoute
  '/api/dna/stats': typeof ApiDnaStatsRoute
  '/api/exchange/credentials': typeof ApiExchangeCredentialsRoute
  '/api/exchange/test': typeof ApiExchangeTestRoute
  '/api/manipulation/alerts': typeof ApiManipulationAlertsRoute
  '/api/market-regime/current': typeof ApiMarketRegimeCurrentRoute
  '/api/market/calendar': typeof ApiMarketCalendarRoute
  '/api/market/history': typeof ApiMarketHistoryRoute
  '/api/market/score-distribution': typeof ApiMarketScoreDistributionRoute
  '/api/marketplace/history': typeof ApiMarketplaceHistoryRoute
  '/api/marketplace/products': typeof ApiMarketplaceProductsRoute
  '/api/prices/$symbol': typeof ApiPricesSymbolRoute
  '/api/risk/evaluate': typeof ApiRiskEvaluateRoute
  '/api/risk/status': typeof ApiRiskStatusRoute
  '/api/sentiment/overview': typeof ApiSentimentOverviewRoute
  '/api/signals/$id': typeof ApiSignalsIdRoute
  '/api/prices/': typeof ApiPricesIndexRoute
  '/api/signals/': typeof ApiSignalsIndexRoute
  '/calibrator/history/$id': typeof AuthenticatedCalibratorHistoryIdRoute
  '/api/bot4x/executions/export': typeof ApiBot4xExecutionsExportRoute
  '/api/calibrator/feedback/$userId': typeof ApiCalibratorFeedbackUserIdRoute
  '/api/calibrator/intent/$userId': typeof ApiCalibratorIntentUserIdRoute
  '/api/calibrator/run/$userId': typeof ApiCalibratorRunUserIdRoute
  '/api/calibrator/state/$userId': typeof ApiCalibratorStateUserIdRoute
  '/api/dna/profile/$userId': typeof ApiDnaProfileUserIdRoute
  '/api/manipulation/snapshot/$pair': typeof ApiManipulationSnapshotPairRoute
  '/api/sentiment/asset/$symbol': typeof ApiSentimentAssetSymbolRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/api': typeof AuthenticatedApiRoute
  '/bot4x': typeof AuthenticatedBot4xRouteWithChildren
  '/calibrator': typeof AuthenticatedCalibratorRouteWithChildren
  '/copy-trading': typeof AuthenticatedCopyTradingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/dna-corrections': typeof AuthenticatedDnaCorrectionsRoute
  '/dna-pairs': typeof AuthenticatedDnaPairsRoute
  '/dna-trader': typeof AuthenticatedDnaTraderRoute
  '/manipulation': typeof AuthenticatedManipulationRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sentiment': typeof AuthenticatedSentimentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/bot4x/onboarding': typeof AuthenticatedBot4xOnboardingRoute
  '/calibrator/history': typeof AuthenticatedCalibratorHistoryRouteWithChildren
  '/api/alerts/feed': typeof ApiAlertsFeedRoute
  '/api/alerts/settings': typeof ApiAlertsSettingsRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bot4x/balance': typeof ApiBot4xBalanceRoute
  '/api/bot4x/config': typeof ApiBot4xConfigRoute
  '/api/bot4x/executions': typeof ApiBot4xExecutionsRouteWithChildren
  '/api/bot4x/start': typeof ApiBot4xStartRoute
  '/api/bot4x/stop': typeof ApiBot4xStopRoute
  '/api/bot4x/telemetry': typeof ApiBot4xTelemetryRoute
  '/api/copilot/chat': typeof ApiCopilotChatRoute
  '/api/copilot/history': typeof ApiCopilotHistoryRoute
  '/api/copy/follows': typeof ApiCopyFollowsRoute
  '/api/dna/stats': typeof ApiDnaStatsRoute
  '/api/exchange/credentials': typeof ApiExchangeCredentialsRoute
  '/api/exchange/test': typeof ApiExchangeTestRoute
  '/api/manipulation/alerts': typeof ApiManipulationAlertsRoute
  '/api/market-regime/current': typeof ApiMarketRegimeCurrentRoute
  '/api/market/history': typeof ApiMarketHistoryRoute
  '/api/market/score-distribution': typeof ApiMarketScoreDistributionRoute
  '/api/marketplace/history': typeof ApiMarketplaceHistoryRoute
  '/api/marketplace/products': typeof ApiMarketplaceProductsRoute
  '/api/prices/$symbol': typeof ApiPricesSymbolRoute
  '/api/risk/evaluate': typeof ApiRiskEvaluateRoute
  '/api/risk/status': typeof ApiRiskStatusRoute
  '/api/sentiment/overview': typeof ApiSentimentOverviewRoute
  '/api/signals/$id': typeof ApiSignalsIdRoute
  '/api/prices': typeof ApiPricesIndexRoute
  '/api/signals': typeof ApiSignalsIndexRoute
  '/calibrator/history/$id': typeof AuthenticatedCalibratorHistoryIdRoute
  '/api/bot4x/executions/export': typeof ApiBot4xExecutionsExportRoute
  '/api/calibrator/feedback/$userId': typeof ApiCalibratorFeedbackUserIdRoute
  '/api/calibrator/intent/$userId': typeof ApiCalibratorIntentUserIdRoute
  '/api/calibrator/run/$userId': typeof ApiCalibratorRunUserIdRoute
  '/api/calibrator/state/$userId': typeof ApiCalibratorStateUserIdRoute
  '/api/dna/profile/$userId': typeof ApiDnaProfileUserIdRoute
  '/api/manipulation/snapshot/$pair': typeof ApiManipulationSnapshotPairRoute
  '/api/sentiment/asset/$symbol': typeof ApiSentimentAssetSymbolRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/api': typeof AuthenticatedApiRoute
  '/_authenticated/bot4x': typeof AuthenticatedBot4xRouteWithChildren
  '/_authenticated/calibrator': typeof AuthenticatedCalibratorRouteWithChildren
  '/_authenticated/copy-trading': typeof AuthenticatedCopyTradingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/dna-corrections': typeof AuthenticatedDnaCorrectionsRoute
  '/_authenticated/dna-pairs': typeof AuthenticatedDnaPairsRoute
  '/_authenticated/dna-trader': typeof AuthenticatedDnaTraderRoute
  '/_authenticated/manipulation': typeof AuthenticatedManipulationRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sentiment': typeof AuthenticatedSentimentRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRoute
  '/_authenticated/bot4x/onboarding': typeof AuthenticatedBot4xOnboardingRoute
  '/_authenticated/calibrator/history': typeof AuthenticatedCalibratorHistoryRouteWithChildren
  '/api/alerts/feed': typeof ApiAlertsFeedRoute
  '/api/alerts/settings': typeof ApiAlertsSettingsRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bot4x/balance': typeof ApiBot4xBalanceRoute
  '/api/bot4x/config': typeof ApiBot4xConfigRoute
  '/api/bot4x/executions': typeof ApiBot4xExecutionsRouteWithChildren
  '/api/bot4x/start': typeof ApiBot4xStartRoute
  '/api/bot4x/stop': typeof ApiBot4xStopRoute
  '/api/bot4x/telemetry': typeof ApiBot4xTelemetryRoute
  '/api/copilot/chat': typeof ApiCopilotChatRoute
  '/api/copilot/history': typeof ApiCopilotHistoryRoute
  '/api/copy/follows': typeof ApiCopyFollowsRoute
  '/api/dna/stats': typeof ApiDnaStatsRoute
  '/api/exchange/credentials': typeof ApiExchangeCredentialsRoute
  '/api/exchange/test': typeof ApiExchangeTestRoute
  '/api/manipulation/alerts': typeof ApiManipulationAlertsRoute
  '/api/market-regime/current': typeof ApiMarketRegimeCurrentRoute
  '/api/market/history': typeof ApiMarketHistoryRoute
  '/api/market/score-distribution': typeof ApiMarketScoreDistributionRoute
  '/api/marketplace/history': typeof ApiMarketplaceHistoryRoute
  '/api/marketplace/products': typeof ApiMarketplaceProductsRoute
  '/api/prices/$symbol': typeof ApiPricesSymbolRoute
  '/api/risk/evaluate': typeof ApiRiskEvaluateRoute
  '/api/risk/status': typeof ApiRiskStatusRoute
  '/api/sentiment/overview': typeof ApiSentimentOverviewRoute
  '/api/signals/$id': typeof ApiSignalsIdRoute
  '/api/prices/': typeof ApiPricesIndexRoute
  '/api/signals/': typeof ApiSignalsIndexRoute
  '/_authenticated/calibrator/history/$id': typeof AuthenticatedCalibratorHistoryIdRoute
  '/api/bot4x/executions/export': typeof ApiBot4xExecutionsExportRoute
  '/api/calibrator/feedback/$userId': typeof ApiCalibratorFeedbackUserIdRoute
  '/api/calibrator/intent/$userId': typeof ApiCalibratorIntentUserIdRoute
  '/api/calibrator/run/$userId': typeof ApiCalibratorRunUserIdRoute
  '/api/calibrator/state/$userId': typeof ApiCalibratorStateUserIdRoute
  '/api/dna/profile/$userId': typeof ApiDnaProfileUserIdRoute
  '/api/manipulation/snapshot/$pair': typeof ApiManipulationSnapshotPairRoute
  '/api/sentiment/asset/$symbol': typeof ApiSentimentAssetSymbolRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/alerts'
    | '/api'
    | '/bot4x'
    | '/calibrator'
    | '/copy-trading'
    | '/dashboard'
    | '/diagnostics'
    | '/dna-corrections'
    | '/dna-pairs'
    | '/dna-trader'
    | '/manipulation'
    | '/marketplace'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/sentiment'
    | '/settings'
    | '/signals'
    | '/bot4x/onboarding'
    | '/calibrator/history'
    | '/api/alerts/feed'
    | '/api/alerts/settings'
    | '/api/auth/me'
    | '/api/bot4x/balance'
    | '/api/bot4x/config'
    | '/api/bot4x/executions'
    | '/api/bot4x/start'
    | '/api/bot4x/stop'
    | '/api/bot4x/telemetry'
    | '/api/copilot/chat'
    | '/api/copilot/history'
    | '/api/copy/follows'
    | '/api/dna/stats'
    | '/api/exchange/credentials'
    | '/api/exchange/test'
    | '/api/manipulation/alerts'
    | '/api/market-regime/current'
    | '/api/market/history'
    | '/api/market/calendar'
    | '/api/market/score-distribution'
    | '/api/marketplace/history'
    | '/api/marketplace/products'
    | '/api/prices/$symbol'
    | '/api/risk/evaluate'
    | '/api/risk/status'
    | '/api/sentiment/overview'
    | '/api/signals/$id'
    | '/api/prices/'
    | '/api/signals/'
    | '/calibrator/history/$id'
    | '/api/bot4x/executions/export'
    | '/api/calibrator/feedback/$userId'
    | '/api/calibrator/intent/$userId'
    | '/api/calibrator/run/$userId'
    | '/api/calibrator/state/$userId'
    | '/api/dna/profile/$userId'
    | '/api/manipulation/snapshot/$pair'
    | '/api/sentiment/asset/$symbol'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/alerts'
    | '/api'
    | '/bot4x'
    | '/calibrator'
    | '/copy-trading'
    | '/dashboard'
    | '/diagnostics'
    | '/dna-corrections'
    | '/dna-pairs'
    | '/dna-trader'
    | '/manipulation'
    | '/marketplace'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/sentiment'
    | '/settings'
    | '/signals'
    | '/bot4x/onboarding'
    | '/calibrator/history'
    | '/api/alerts/feed'
    | '/api/alerts/settings'
    | '/api/auth/me'
    | '/api/bot4x/balance'
    | '/api/bot4x/config'
    | '/api/bot4x/executions'
    | '/api/bot4x/start'
    | '/api/bot4x/stop'
    | '/api/bot4x/telemetry'
    | '/api/copilot/chat'
    | '/api/copilot/history'
    | '/api/copy/follows'
    | '/api/dna/stats'
    | '/api/exchange/credentials'
    | '/api/exchange/test'
    | '/api/manipulation/alerts'
    | '/api/market-regime/current'
    | '/api/market/history'
    | '/api/market/score-distribution'
    | '/api/marketplace/history'
    | '/api/marketplace/products'
    | '/api/prices/$symbol'
    | '/api/risk/evaluate'
    | '/api/risk/status'
    | '/api/sentiment/overview'
    | '/api/signals/$id'
    | '/api/prices'
    | '/api/signals'
    | '/calibrator/history/$id'
    | '/api/bot4x/executions/export'
    | '/api/calibrator/feedback/$userId'
    | '/api/calibrator/intent/$userId'
    | '/api/calibrator/run/$userId'
    | '/api/calibrator/state/$userId'
    | '/api/dna/profile/$userId'
    | '/api/manipulation/snapshot/$pair'
    | '/api/sentiment/asset/$symbol'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/alerts'
    | '/_authenticated/api'
    | '/_authenticated/bot4x'
    | '/_authenticated/calibrator'
    | '/_authenticated/copy-trading'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostics'
    | '/_authenticated/dna-corrections'
    | '/_authenticated/dna-pairs'
    | '/_authenticated/dna-trader'
    | '/_authenticated/manipulation'
    | '/_authenticated/marketplace'
    | '/_authenticated/onboarding'
    | '/_authenticated/pricing'
    | '/_authenticated/profile'
    | '/_authenticated/sentiment'
    | '/_authenticated/settings'
    | '/_authenticated/signals'
    | '/_authenticated/bot4x/onboarding'
    | '/_authenticated/calibrator/history'
    | '/api/alerts/feed'
    | '/api/alerts/settings'
    | '/api/auth/me'
    | '/api/bot4x/balance'
    | '/api/bot4x/config'
    | '/api/bot4x/executions'
    | '/api/bot4x/start'
    | '/api/bot4x/stop'
    | '/api/bot4x/telemetry'
    | '/api/copilot/chat'
    | '/api/copilot/history'
    | '/api/copy/follows'
    | '/api/dna/stats'
    | '/api/exchange/credentials'
    | '/api/exchange/test'
    | '/api/manipulation/alerts'
    | '/api/market-regime/current'
    | '/api/market/history'
    | '/api/market/score-distribution'
    | '/api/marketplace/history'
    | '/api/marketplace/products'
    | '/api/prices/$symbol'
    | '/api/risk/evaluate'
    | '/api/risk/status'
    | '/api/sentiment/overview'
    | '/api/signals/$id'
    | '/api/prices/'
    | '/api/signals/'
    | '/_authenticated/calibrator/history/$id'
    | '/api/bot4x/executions/export'
    | '/api/calibrator/feedback/$userId'
    | '/api/calibrator/intent/$userId'
    | '/api/calibrator/run/$userId'
    | '/api/calibrator/state/$userId'
    | '/api/dna/profile/$userId'
    | '/api/manipulation/snapshot/$pair'
    | '/api/sentiment/asset/$symbol'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiAlertsFeedRoute: typeof ApiAlertsFeedRoute
  ApiAlertsSettingsRoute: typeof ApiAlertsSettingsRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiBot4xBalanceRoute: typeof ApiBot4xBalanceRoute
  ApiBot4xDemoOrderRoute: typeof ApiBot4xDemoOrderRoute
  ApiBot4xConfigRoute: typeof ApiBot4xConfigRoute
  ApiBot4xExecutionsRoute: typeof ApiBot4xExecutionsRouteWithChildren
  ApiBot4xStartRoute: typeof ApiBot4xStartRoute
  ApiBot4xStopRoute: typeof ApiBot4xStopRoute
  ApiBot4xTelemetryRoute: typeof ApiBot4xTelemetryRoute
  ApiCopilotChatRoute: typeof ApiCopilotChatRoute
  ApiCopilotHistoryRoute: typeof ApiCopilotHistoryRoute
  ApiCopyFollowsRoute: typeof ApiCopyFollowsRoute
  ApiDnaStatsRoute: typeof ApiDnaStatsRoute
  ApiExchangeCredentialsRoute: typeof ApiExchangeCredentialsRoute
  ApiExchangeTestRoute: typeof ApiExchangeTestRoute
  ApiManipulationAlertsRoute: typeof ApiManipulationAlertsRoute
  ApiMarketRegimeCurrentRoute: typeof ApiMarketRegimeCurrentRoute
  ApiMarketHistoryRoute: typeof ApiMarketHistoryRoute
  ApiMarketCalendarRoute: typeof ApiMarketCalendarRoute
  ApiMarketScoreDistributionRoute: typeof ApiMarketScoreDistributionRoute
  ApiMarketplaceHistoryRoute: typeof ApiMarketplaceHistoryRoute
  ApiMarketplaceProductsRoute: typeof ApiMarketplaceProductsRoute
  ApiPricesSymbolRoute: typeof ApiPricesSymbolRoute
  ApiRiskEvaluateRoute: typeof ApiRiskEvaluateRoute
  ApiRiskStatusRoute: typeof ApiRiskStatusRoute
  ApiSentimentOverviewRoute: typeof ApiSentimentOverviewRoute
  ApiSignalsIdRoute: typeof ApiSignalsIdRoute
  ApiPricesIndexRoute: typeof ApiPricesIndexRoute
  ApiSignalsIndexRoute: typeof ApiSignalsIndexRoute
  ApiCalibratorFeedbackUserIdRoute: typeof ApiCalibratorFeedbackUserIdRoute
  ApiCalibratorIntentUserIdRoute: typeof ApiCalibratorIntentUserIdRoute
  ApiCalibratorRunUserIdRoute: typeof ApiCalibratorRunUserIdRoute
  ApiCalibratorStateUserIdRoute: typeof ApiCalibratorStateUserIdRoute
  ApiDnaProfileUserIdRoute: typeof ApiDnaProfileUserIdRoute
  ApiManipulationSnapshotPairRoute: typeof ApiManipulationSnapshotPairRoute
  ApiSentimentAssetSymbolRoute: typeof ApiSentimentAssetSymbolRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sentiment': {
      id: '/_authenticated/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof AuthenticatedSentimentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manipulation': {
      id: '/_authenticated/manipulation'
      path: '/manipulation'
      fullPath: '/manipulation'
      preLoaderRoute: typeof AuthenticatedManipulationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dna-trader': {
      id: '/_authenticated/dna-trader'
      path: '/dna-trader'
      fullPath: '/dna-trader'
      preLoaderRoute: typeof AuthenticatedDnaTraderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dna-pairs': {
      id: '/_authenticated/dna-pairs'
      path: '/dna-pairs'
      fullPath: '/dna-pairs'
      preLoaderRoute: typeof AuthenticatedDnaPairsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dna-corrections': {
      id: '/_authenticated/dna-corrections'
      path: '/dna-corrections'
      fullPath: '/dna-corrections'
      preLoaderRoute: typeof AuthenticatedDnaCorrectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/copy-trading': {
      id: '/_authenticated/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof AuthenticatedCopyTradingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calibrator': {
      id: '/_authenticated/calibrator'
      path: '/calibrator'
      fullPath: '/calibrator'
      preLoaderRoute: typeof AuthenticatedCalibratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bot4x': {
      id: '/_authenticated/bot4x'
      path: '/bot4x'
      fullPath: '/bot4x'
      preLoaderRoute: typeof AuthenticatedBot4xRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api': {
      id: '/_authenticated/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AuthenticatedApiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/signals/': {
      id: '/api/signals/'
      path: '/api/signals'
      fullPath: '/api/signals/'
      preLoaderRoute: typeof ApiSignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices/': {
      id: '/api/prices/'
      path: '/api/prices'
      fullPath: '/api/prices/'
      preLoaderRoute: typeof ApiPricesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals/$id': {
      id: '/api/signals/$id'
      path: '/api/signals/$id'
      fullPath: '/api/signals/$id'
      preLoaderRoute: typeof ApiSignalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentiment/overview': {
      id: '/api/sentiment/overview'
      path: '/api/sentiment/overview'
      fullPath: '/api/sentiment/overview'
      preLoaderRoute: typeof ApiSentimentOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/risk/status': {
      id: '/api/risk/status'
      path: '/api/risk/status'
      fullPath: '/api/risk/status'
      preLoaderRoute: typeof ApiRiskStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/risk/evaluate': {
      id: '/api/risk/evaluate'
      path: '/api/risk/evaluate'
      fullPath: '/api/risk/evaluate'
      preLoaderRoute: typeof ApiRiskEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices/$symbol': {
      id: '/api/prices/$symbol'
      path: '/api/prices/$symbol'
      fullPath: '/api/prices/$symbol'
      preLoaderRoute: typeof ApiPricesSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace/products': {
      id: '/api/marketplace/products'
      path: '/api/marketplace/products'
      fullPath: '/api/marketplace/products'
      preLoaderRoute: typeof ApiMarketplaceProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketplace/history': {
      id: '/api/marketplace/history'
      path: '/api/marketplace/history'
      fullPath: '/api/marketplace/history'
      preLoaderRoute: typeof ApiMarketplaceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/score-distribution': {
      id: '/api/market/score-distribution'
      path: '/api/market/score-distribution'
      fullPath: '/api/market/score-distribution'
      preLoaderRoute: typeof ApiMarketScoreDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/calendar': {
      id: '/api/market/calendar'
      path: '/api/market/calendar'
      fullPath: '/api/market/calendar'
      preLoaderRoute: typeof ApiMarketCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/history': {
      id: '/api/market/history'
      path: '/api/market/history'
      fullPath: '/api/market/history'
      preLoaderRoute: typeof ApiMarketHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-regime/current': {
      id: '/api/market-regime/current'
      path: '/api/market-regime/current'
      fullPath: '/api/market-regime/current'
      preLoaderRoute: typeof ApiMarketRegimeCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manipulation/alerts': {
      id: '/api/manipulation/alerts'
      path: '/api/manipulation/alerts'
      fullPath: '/api/manipulation/alerts'
      preLoaderRoute: typeof ApiManipulationAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange/test': {
      id: '/api/exchange/test'
      path: '/api/exchange/test'
      fullPath: '/api/exchange/test'
      preLoaderRoute: typeof ApiExchangeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange/credentials': {
      id: '/api/exchange/credentials'
      path: '/api/exchange/credentials'
      fullPath: '/api/exchange/credentials'
      preLoaderRoute: typeof ApiExchangeCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dna/stats': {
      id: '/api/dna/stats'
      path: '/api/dna/stats'
      fullPath: '/api/dna/stats'
      preLoaderRoute: typeof ApiDnaStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copy/follows': {
      id: '/api/copy/follows'
      path: '/api/copy/follows'
      fullPath: '/api/copy/follows'
      preLoaderRoute: typeof ApiCopyFollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/history': {
      id: '/api/copilot/history'
      path: '/api/copilot/history'
      fullPath: '/api/copilot/history'
      preLoaderRoute: typeof ApiCopilotHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/chat': {
      id: '/api/copilot/chat'
      path: '/api/copilot/chat'
      fullPath: '/api/copilot/chat'
      preLoaderRoute: typeof ApiCopilotChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot4x/telemetry': {
      id: '/api/bot4x/telemetry'
      path: '/api/bot4x/telemetry'
      fullPath: '/api/bot4x/telemetry'
      preLoaderRoute: typeof ApiBot4xTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot4x/stop': {
      id: '/api/bot4x/stop'
      path: '/api/bot4x/stop'
      fullPath: '/api/bot4x/stop'
      preLoaderRoute: typeof ApiBot4xStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot4x/start': {
      id: '/api/bot4x/start'
      path: '/api/bot4x/start'
      fullPath: '/api/bot4x/start'
      preLoaderRoute: typeof ApiBot4xStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot4x/executions': {
      id: '/api/bot4x/executions'
      path: '/api/bot4x/executions'
      fullPath: '/api/bot4x/executions'
      preLoaderRoute: typeof ApiBot4xExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot4x/config': {
      id: '/api/bot4x/config'
      path: '/api/bot4x/config'
      fullPath: '/api/bot4x/config'
      preLoaderRoute: typeof ApiBot4xConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot4x/demo-order'
    '/api/bot4x/demo-order'
    '/api/bot4x/demo-order'
    '/api/bot4x/balance': {
      id: '/api/bot4x/balance'
      path: '/api/bot4x/balance'
      fullPath: '/api/bot4x/balance'
      preLoaderRoute: typeof ApiBot4xBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot4x/demo-order': {
      id: '/api/bot4x/demo-order'
      path: '/api/bot4x/demo-order'
      fullPath: '/api/bot4x/demo-order'
      preLoaderRoute: typeof ApiBot4xDemoOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/settings': {
      id: '/api/alerts/settings'
      path: '/api/alerts/settings'
      fullPath: '/api/alerts/settings'
      preLoaderRoute: typeof ApiAlertsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/feed': {
      id: '/api/alerts/feed'
      path: '/api/alerts/feed'
      fullPath: '/api/alerts/feed'
      preLoaderRoute: typeof ApiAlertsFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calibrator/history': {
      id: '/_authenticated/calibrator/history'
      path: '/history'
      fullPath: '/calibrator/history'
      preLoaderRoute: typeof AuthenticatedCalibratorHistoryRouteImport
      parentRoute: typeof AuthenticatedCalibratorRoute
    }
    '/_authenticated/bot4x/onboarding': {
      id: '/_authenticated/bot4x/onboarding'
      path: '/onboarding'
      fullPath: '/bot4x/onboarding'
      preLoaderRoute: typeof AuthenticatedBot4xOnboardingRouteImport
      parentRoute: typeof AuthenticatedBot4xRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentiment/asset/$symbol': {
      id: '/api/sentiment/asset/$symbol'
      path: '/api/sentiment/asset/$symbol'
      fullPath: '/api/sentiment/asset/$symbol'
      preLoaderRoute: typeof ApiSentimentAssetSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manipulation/snapshot/$pair': {
      id: '/api/manipulation/snapshot/$pair'
      path: '/api/manipulation/snapshot/$pair'
      fullPath: '/api/manipulation/snapshot/$pair'
      preLoaderRoute: typeof ApiManipulationSnapshotPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dna/profile/$userId': {
      id: '/api/dna/profile/$userId'
      path: '/api/dna/profile/$userId'
      fullPath: '/api/dna/profile/$userId'
      preLoaderRoute: typeof ApiDnaProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calibrator/state/$userId': {
      id: '/api/calibrator/state/$userId'
      path: '/api/calibrator/state/$userId'
      fullPath: '/api/calibrator/state/$userId'
      preLoaderRoute: typeof ApiCalibratorStateUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calibrator/run/$userId': {
      id: '/api/calibrator/run/$userId'
      path: '/api/calibrator/run/$userId'
      fullPath: '/api/calibrator/run/$userId'
      preLoaderRoute: typeof ApiCalibratorRunUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calibrator/intent/$userId': {
      id: '/api/calibrator/intent/$userId'
      path: '/api/calibrator/intent/$userId'
      fullPath: '/api/calibrator/intent/$userId'
      preLoaderRoute: typeof ApiCalibratorIntentUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calibrator/feedback/$userId': {
      id: '/api/calibrator/feedback/$userId'
      path: '/api/calibrator/feedback/$userId'
      fullPath: '/api/calibrator/feedback/$userId'
      preLoaderRoute: typeof ApiCalibratorFeedbackUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot4x/executions/export': {
      id: '/api/bot4x/executions/export'
      path: '/export'
      fullPath: '/api/bot4x/executions/export'
      preLoaderRoute: typeof ApiBot4xExecutionsExportRouteImport
      parentRoute: typeof ApiBot4xExecutionsRoute
    }
    '/_authenticated/calibrator/history/$id': {
      id: '/_authenticated/calibrator/history/$id'
      path: '/$id'
      fullPath: '/calibrator/history/$id'
      preLoaderRoute: typeof AuthenticatedCalibratorHistoryIdRouteImport
      parentRoute: typeof AuthenticatedCalibratorHistoryRoute
    }
  }
}

interface AuthenticatedBot4xRouteChildren {
  AuthenticatedBot4xOnboardingRoute: typeof AuthenticatedBot4xOnboardingRoute
}

const AuthenticatedBot4xRouteChildren: AuthenticatedBot4xRouteChildren = {
  AuthenticatedBot4xOnboardingRoute: AuthenticatedBot4xOnboardingRoute,
}

const AuthenticatedBot4xRouteWithChildren =
  AuthenticatedBot4xRoute._addFileChildren(AuthenticatedBot4xRouteChildren)

interface AuthenticatedCalibratorHistoryRouteChildren {
  AuthenticatedCalibratorHistoryIdRoute: typeof AuthenticatedCalibratorHistoryIdRoute
}

const AuthenticatedCalibratorHistoryRouteChildren: AuthenticatedCalibratorHistoryRouteChildren =
  {
    AuthenticatedCalibratorHistoryIdRoute:
      AuthenticatedCalibratorHistoryIdRoute,
  }

const AuthenticatedCalibratorHistoryRouteWithChildren =
  AuthenticatedCalibratorHistoryRoute._addFileChildren(
    AuthenticatedCalibratorHistoryRouteChildren,
  )

interface AuthenticatedCalibratorRouteChildren {
  AuthenticatedCalibratorHistoryRoute: typeof AuthenticatedCalibratorHistoryRouteWithChildren
}

const AuthenticatedCalibratorRouteChildren: AuthenticatedCalibratorRouteChildren =
  {
    AuthenticatedCalibratorHistoryRoute:
      AuthenticatedCalibratorHistoryRouteWithChildren,
  }

const AuthenticatedCalibratorRouteWithChildren =
  AuthenticatedCalibratorRoute._addFileChildren(
    AuthenticatedCalibratorRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedApiRoute: typeof AuthenticatedApiRoute
  AuthenticatedBot4xRoute: typeof AuthenticatedBot4xRouteWithChildren
  AuthenticatedCalibratorRoute: typeof AuthenticatedCalibratorRouteWithChildren
  AuthenticatedCopyTradingRoute: typeof AuthenticatedCopyTradingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedDnaCorrectionsRoute: typeof AuthenticatedDnaCorrectionsRoute
  AuthenticatedDnaPairsRoute: typeof AuthenticatedDnaPairsRoute
  AuthenticatedDnaTraderRoute: typeof AuthenticatedDnaTraderRoute
  AuthenticatedManipulationRoute: typeof AuthenticatedManipulationRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSentimentRoute: typeof AuthenticatedSentimentRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedApiRoute: AuthenticatedApiRoute,
  AuthenticatedBot4xRoute: AuthenticatedBot4xRouteWithChildren,
  AuthenticatedCalibratorRoute: AuthenticatedCalibratorRouteWithChildren,
  AuthenticatedCopyTradingRoute: AuthenticatedCopyTradingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedDnaCorrectionsRoute: AuthenticatedDnaCorrectionsRoute,
  AuthenticatedDnaPairsRoute: AuthenticatedDnaPairsRoute,
  AuthenticatedDnaTraderRoute: AuthenticatedDnaTraderRoute,
  AuthenticatedManipulationRoute: AuthenticatedManipulationRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSentimentRoute: AuthenticatedSentimentRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiBot4xExecutionsRouteChildren {
  ApiBot4xExecutionsExportRoute: typeof ApiBot4xExecutionsExportRoute
}

const ApiBot4xExecutionsRouteChildren: ApiBot4xExecutionsRouteChildren = {
  ApiBot4xExecutionsExportRoute: ApiBot4xExecutionsExportRoute,
}

const ApiBot4xExecutionsRouteWithChildren =
  ApiBot4xExecutionsRoute._addFileChildren(ApiBot4xExecutionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiAlertsFeedRoute: ApiAlertsFeedRoute,
  ApiAlertsSettingsRoute: ApiAlertsSettingsRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiBot4xBalanceRoute: ApiBot4xBalanceRoute,
  ApiBot4xDemoOrderRoute: ApiBot4xDemoOrderRoute,
  ApiBot4xConfigRoute: ApiBot4xConfigRoute,
  ApiBot4xExecutionsRoute: ApiBot4xExecutionsRouteWithChildren,
  ApiBot4xStartRoute: ApiBot4xStartRoute,
  ApiBot4xStopRoute: ApiBot4xStopRoute,
  ApiBot4xTelemetryRoute: ApiBot4xTelemetryRoute,
  ApiCopilotChatRoute: ApiCopilotChatRoute,
  ApiCopilotHistoryRoute: ApiCopilotHistoryRoute,
  ApiCopyFollowsRoute: ApiCopyFollowsRoute,
  ApiDnaStatsRoute: ApiDnaStatsRoute,
  ApiExchangeCredentialsRoute: ApiExchangeCredentialsRoute,
  ApiExchangeTestRoute: ApiExchangeTestRoute,
  ApiManipulationAlertsRoute: ApiManipulationAlertsRoute,
  ApiMarketRegimeCurrentRoute: ApiMarketRegimeCurrentRoute,
  ApiMarketHistoryRoute: ApiMarketHistoryRoute,
  ApiMarketCalendarRoute: ApiMarketCalendarRoute,
  ApiMarketScoreDistributionRoute: ApiMarketScoreDistributionRoute,
  ApiMarketplaceHistoryRoute: ApiMarketplaceHistoryRoute,
  ApiMarketplaceProductsRoute: ApiMarketplaceProductsRoute,
  ApiPricesSymbolRoute: ApiPricesSymbolRoute,
  ApiRiskEvaluateRoute: ApiRiskEvaluateRoute,
  ApiRiskStatusRoute: ApiRiskStatusRoute,
  ApiSentimentOverviewRoute: ApiSentimentOverviewRoute,
  ApiSignalsIdRoute: ApiSignalsIdRoute,
  ApiPricesIndexRoute: ApiPricesIndexRoute,
  ApiSignalsIndexRoute: ApiSignalsIndexRoute,
  ApiCalibratorFeedbackUserIdRoute: ApiCalibratorFeedbackUserIdRoute,
  ApiCalibratorIntentUserIdRoute: ApiCalibratorIntentUserIdRoute,
  ApiCalibratorRunUserIdRoute: ApiCalibratorRunUserIdRoute,
  ApiCalibratorStateUserIdRoute: ApiCalibratorStateUserIdRoute,
  ApiDnaProfileUserIdRoute: ApiDnaProfileUserIdRoute,
  ApiManipulationSnapshotPairRoute: ApiManipulationSnapshotPairRoute,
  ApiSentimentAssetSymbolRoute: ApiSentimentAssetSymbolRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}